### ISSUE TITLE
If the amount is less than total, it shouldn't add more fruits

### ISSUE THREAD

**Issue by KhairUnNisa10** [ShoaibAhmed230/fruit-store-website-using-javascript#3]
![image](https://user-images.githubusercontent.com/49787331/88774434-e11b7d80-d19c-11ea-8aa2-a54eb487b22f.png)

If the user total amount reaches to wallet amount, it should alert which is perfect in your program. But it shouldn't add the amount again with minus.

**Comment by KhairUnNisa10** [comment]
This issue is still same.

**Comment by ShoaibAhmed230** [comment]
Okay I'll check it out
