### ISSUE TITLE
Defining Variables

### ISSUE THREAD

**Issue by KhairUnNisa10** [ShoaibAhmed230/fruit-store-website-using-javascript#4]
https://github.com/ShoaibAhmed230/fruit-store-website-using-javascript/blob/48f2d4b744b1b75dd3f25988a60c3fec3d8ff6e2/java.js#L3-L18

You can also define many variables at the same time like this:
let/var = example1,
example2,
example3,
example4,
examplen;

So you don't have to write the let/var everytime but you can write it once and define as many variables as you want separating by a comma.

**Comment by ShoaibAhmed230** [comment]
yes ma'am you are saying right ...actually ma'am  its project not completed
.. i still working on this project

**Comment by ShoaibAhmed230** [comment]
I presented this project with the idea that I would get some stars instead
of zero stars

**Comment by KhairUnNisa10** [comment]
No issues, this is not an error, I am just telling you to not have a repetition in your code.

**Comment by ShoaibAhmed230** [comment]
Okay .no problem ma'am...
